version: '3.1'
services:
  mysql:
    image: docker.io/library/mysql:8.0
    container_name: kim_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - kimnet
    ports:
      - "3306:3306"
    volumes:
      - ~/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: docker.io/library/redis:6.2
    container_name: kim_redis
    command: redis-server
    networks:
      - kimnet
    ports:
      - "6379:6379"
    volumes:
      - ~/data/redis:/data

